# Generated by Django 5.1 on 2024-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('deliver', 'Deliver'), ('client', 'Client')], max_length=30),
        ),
    ]
