# Generated by Django 5.1 on 2024-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0004_product_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
