# Generated by Django 5.1 on 2024-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('site_logo', models.ImageField(blank=True, upload_to='logos/')),
                ('site_favicon', models.ImageField(blank=True, upload_to='favicons/')),
                ('color_scheme', models.CharField(blank=True, max_length=7)),
                ('site_font', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('social_media', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('smtp_server', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
            ],
        ),
    ]
