# Generated by Django 5.1 on 2024-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0010_remove_catalog_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
