# Generated by Django 5.1 on 2024-08-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0011_alter_product_options_alter_catalog_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
