# Generated by Django 5.1 on 2024-08-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0018_faq_order_return_review_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='binzi.order'),
        ),
    ]
