# Generated by Django 5.1 on 2024-08-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0021_alter_usersetting_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
