# Generated by Django 5.1 on 2024-09-01 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0024_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
