# Generated by Django 5.1 on 2024-09-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0026_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
