# Generated by Django 5.1 on 2024-10-06 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0028_deliverrating_productrating_servicequalityrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCommandProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('official_release_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pre_command_products/')),
                ('video_publicity', models.FileField(blank=True, null=True, upload_to='pre_command_videos/')),
                ('new_innovation', models.TextField()),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('eshop_location', models.CharField(max_length=255)),
            ],
        ),
    ]
