# Generated by Django 5.1 on 2024-10-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0032_precommandpayment_delete_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreCommandPayment',
            new_name='PreCommandTransaction',
        ),
    ]
