# Generated by Django 5.1 on 2024-10-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0033_rename_precommandpayment_precommandtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precommandtransaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='precommandtransaction',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='precommandtransaction',
            name='status',
            field=models.CharField(default='non-paid', max_length=20),
        ),
    ]
