# Generated by Django 5.1 on 2024-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binzi', '0034_rename_transaction_date_precommandtransaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
